### ISSUE TITLE
Does this work with arm ?

### ISSUE THREAD

**Issue by hammad2224** [rdbo/libmem#1]
Hi,

I would like to use mem.read for reading android memory simple functions like
so it will be basically 
long addressreturn=Read<int>(address);
string stringreturn=ReadString(address,ize,bytesToRead);

#if defined (__arm__)
	//arm read syscall for process_vm_writev 377
	int syscallWrite = 377;
	//arm read syscall for process_vm_readv 376
	int syscallRead = 376;

Problem with me is i get read data error because entity might be removed and i try to read it it cause the memory stack crouption. and i get detected.

if you build that class for me i can pay you
i know its quick work for you but it will support your time.
please do let me know my discord is Hammad2224#9851

Thanks 
Regards,
Hammad

**Comment by rdbo** [comment]
For now, it doesn't have support for ARM, as I'm still finishing the PC stuff. I might add support in the future once I have deeper knowledge in ARM.
