### ISSUE TITLE
Are gateway's on the mem::in::detour_trampoline functional? 

### ISSUE THREAD

**Issue by turtiustrek** [rdbo/libmem#16]
I have a [project](https://github.com/turtiustrek/taskmanager) where this library was needed for taskmanager(thank you!) and while working on it, I found something rather strange with ``` mem::in::detour_trampoline``` (or I am using it incorrectly) as the trampoline executes but the returning gateway fails to return.
this is how the detour was created:
```o_function=  (function_t) mem::in::detour_trampoline(IsServer, (void *)IsServerHook, mem::in::detour_size(MEM_ASM_x86_JMP64), MEM_ASM_x86_JMP64);```
and here is the respective hook:
```
typedef bool(* function_t)(void *ret);
bool __fastcall IsServerHook(void *ret)
{
    GlobalSettings = ret;
    std::cout << "exe" << std::endl;
    return o_function(ret);
}
```
it prints out the ```exe``` string and then upon return, process crashes.
before jumping(executes): 
![image](https://user-images.githubusercontent.com/12457839/112697073-b2c77c80-8ea8-11eb-8761-f39c992bb332.png)

returning back(crashes on 'ret' instruction):
![image](https://user-images.githubusercontent.com/12457839/112697015-9a576200-8ea8-11eb-8a44-1334ffd55400.png)

**Comment by rdbo** [comment]
Can you send a screenshot of the disassembly of the original function (before hooking), of the function after hooking, and the destination function (the one that's being called on the hook) so I can check this out? I know that you've sent screenshots already, but the address of the JMP in the first one (I assume it's the hooked function) is not the same as the address in the second one and I need to see the whole assembly to check whether something is wrong or not.
Meanwhile, I'll take a look at the code and see if there's anything wrong.
Also, good job in the task manager project.

**Comment by turtiustrek** [comment]
Sorry those were the wrong screenshots. 
IsServer function without any hooks in place:
![unmodded](https://user-images.githubusercontent.com/12457839/112718587-e12f7100-8f15-11eb-96c1-4070a1bc3f21.PNG)
Dll is now injected and the IsServer function is modded
![hook_in_place](https://user-images.githubusercontent.com/12457839/112718611-002e0300-8f16-11eb-8839-55fa6de45d95.PNG)
Hook called and jumps
![actual_hook](https://user-images.githubusercontent.com/12457839/112718681-6581f400-8f16-11eb-923d-b52bef528c7b.PNG)
crashed occurred while calling the contents of rax 
![crash_occures](https://user-images.githubusercontent.com/12457839/112718712-9104de80-8f16-11eb-8596-8f2ad819a72e.PNG)
location at rax:
![rax_jumped_to](https://user-images.githubusercontent.com/12457839/112718719-aa0d8f80-8f16-11eb-88df-a89241eeaa23.PNG)
DLL code:
```
typedef bool(* function_t)(void *ret);
function_t o_function;
bool __fastcall IsServerHook(void *ret)
{
    std::cout << "exe" << std::endl;
    return o_function(ret);
}
```
```
 o_function=  (function_t) mem::in::detour_trampoline(IsServer, (void *)IsServerHook, mem::in::detour_size(MEM_ASM_x86_JMP64), MEM_ASM_x86_JMP64);
```
Hope this helps and thanks

**Comment by rdbo** [comment]
One problem that I noticed is that the detour size is wrong. `mem::in::detour_size` returns the minimum size for a detour, but as you don't want to save incomplete instructions, you have to round it up according to the next instruction size. For `MEM_ASM_x86_JMP64` on x64, `mem::in::detour_size` will return '14'. If you look at the bytes of the original function, you can see that 14 bytes is not enough, as it will stop on the byte `DB` from the 3rd instruction of the function, missing 2 bytes. This means that the gateway is gonna run an incomplete instruction and from then, anything could happen. To solve this issue, just set the detour size to `16`, which is the minimum size for `MEM_ASM_x86_JMP64` plus '2' to fit the rest of the instruction:
```c++
 o_function=  (function_t) mem::in::detour_trampoline(IsServer, (void *)IsServerHook, 16, MEM_ASM_x86_JMP64);
```

**Comment by turtiustrek** [comment]
Got it further as its returning back to the original function with the changes you said above but crashes right after. 
![calling contents of raz](https://user-images.githubusercontent.com/12457839/112750640-240b4a80-8fe3-11eb-8efe-60b79d27fa8d.PNG)
![gatway returns back](https://user-images.githubusercontent.com/12457839/112750649-39807480-8fe3-11eb-8213-8684f6c62cd7.PNG)

**Comment by rdbo** [comment]
Where exactly does it crash?

**Comment by turtiustrek** [comment]
highlighted in gray, its an unknown instruction(most likely some corruption) which just so happens to point RIP to invalid address and therefore the process crashes

**Comment by rdbo** [comment]
It's not an unknown instruction. We're overwriting bytes in the start of the function, which is messing with the disassembly of a few instructions after that, including this one. The jump from the gateway doesn't go on the first byte of this unknown instruction, it goes to a part of it where it is a valid instruction. In this case, the instruction is `XOR EAX, ESP`, which is `48 33 C4`. It is preserved from the original function. I don't see how this instruction could be causing a crash though.

**Comment by turtiustrek** [comment]
Ah, i see as that part is from the original function . Well i did not post where RIP was so in that case here it is and my previous statement about where 'it crashes' was wrong. Apologizes for that. 
![image](https://user-images.githubusercontent.com/12457839/112756645-9427c980-8fff-11eb-974b-1d213d2fd6cd.png)

**Comment by rdbo** [comment]
I don't think this is related to the detour anymore. It's another function that has an `INT 29` instruction, which even though I'm not sure what it does, it probably stops the process for some reason. Maybe it works similarly to the `INT 3` instruction, which is a breakpoint.

**Comment by rdbo** [comment]
I don't think this is related to the detour anymore. The process is expected to stop because it's running an `INT` instruction (interrupt).

**Comment by turtiustrek** [comment]
Yes, it was indeed interrupt related. Apologizes figured it out right after posting the picture above.
