### ISSUE TITLE
[request]publish to vcpkg

### ISSUE THREAD

**Issue by Gn3po4g** [rdbo/libmem#169]
vcpkg can manage packages for vs projects and cmake projects on Windows. Hope we can install via 
```shell
vcpkg install libmem
``` 
one day without having to download binaries.

**Comment by luadebug** [comment]
Maybe one day if requirements would get fulfilled. https://github.com/microsoft/vcpkg/pull/41345

**Comment by luadebug** [comment]
> vcpkg can manage packages for vs projects and cmake projects on Windows. Hope we can install via 
> ```shell
> vcpkg install libmem
> ``` 
> one day without having to download binaries.

You can check out xrepo and xmake. It has Libmem port.

**Comment by Gn3po4g** [comment]
awesome♥️
