### ISSUE TITLE
suggestions: unprotecting memory, installing patches

### ISSUE THREAD

**Issue by alextwothousand** [rdbo/libmem#17]
I wanted to suggest the ability to:

* Unprotect memory
* Install a NOP patch
* Install a JMP patch
* Install a CALL patch

I would be more than happy to assist, if need be?

**Comment by rdbo** [comment]
These are all already possible on version 3.3.3
They will also be possible on V4.0 once I finish it.
The respective API calls are gonna be:
`LM_ProtectMemory(Ex)`
`LM_SetMemory(Ex)`
`LM_DetourCode(Ex)`

LM_ProtectMemory allows you to protect memory and save the old protection so you can restore it later
LM_SetMemory sets a memory region to a single byte (in the case of x86 NOP'ing, you have to set to 0x90)
LM_DetourCode allows you to place a hook somewhere with multiple methods, such as JMP, CALL, RET

The version 3 API calls are:
`mem_(in/ex)_protect`
`mem_(in/ex)_set`
`mem_(in/ex)_detour`

By the way, I appreciate the help, you are the first one to offer. Just gotta finish porting V3 to V4, adding support to ARM/ARM64, documentation, etc. I think I might finish V4 soon, so stayed tuned

**Comment by alextwothousand** [comment]
Thank you! and not a worry at all.

Could you provide me with an example for mem_in_detour? I'm not so sure if its able to install a RETN patch - the confusing part is what I should use as the destination, haha

**Comment by alextwothousand** [comment]
Never mind, was able to figure it out!
