### ISSUE TITLE
Small doc correction for Rust LM_FindSymbolAddress

### ISSUE THREAD

**Issue by MolotovCherry** [rdbo/libmem#220]
On the [rust docs for LM_FindSymbolAddress](https://github.com/rdbo/libmem/blob/master/docs/rust/LM_FindSymbolAddress.md), for the `name` param it states:
> _name: C string containing the name of the symbol_

But strictly speaking, the c string is already handled internally, and passing a normal rust string is OK. This param description is OK on `LM_SymbolAddressDemangled`

**Comment by rdbo** [comment]
Since the Rust bindings are being rework on, the current docs will probably get deprecated
I'm putting brief documentation using `///` on top of the methods to make up for it, and also will be easier to access from the code editor/IDE
