### ISSUE TITLE
[TUT] What should it looks like of mem::in::detour_trampoline in current version?

### ISSUE THREAD

**Issue by laper32** [rdbo/libmem#24]
Hi, by referencing your AssaultCube-Multihack of this line:
```cpp
Data::oSwapBuffers = (SwapBuffers_t)mem::in::detour_trampoline(Data::pSwapBuffers, (mem::voidptr_t)Hooks::SwapBuffers, Data::szSwapBuffers, mem::MEM_DT_M1);
```
see [here](https://github.com/rdbo/AssaultCube-Multihack/blob/main/src/hooks/hooks.cpp#L6)

What should it looks like in current version of libmem?

This is the code what I've made:
```cpp
lm_module_t opengl32;
namespace gl
{
  void* SwapBuffers;
}
using SwapBuffers_t = BOOL(__stdcall*)(_In_ HDC hDC);
namespace hook
{
  namespace gl
  {
    SwapBuffers_t SwapBuffers;
  }
}

// idk why crashed...
void Init(HMODULE hModule)
{
  LM_GetModule(LM_MOD_BY_STR, (void*)LM_STR("OPENGL32.dll"), &opengl32);

  gl::SwapBuffers = LM_GetSymbol(opengl32, (lm_cstring_t)"wglSwapBuffers");
  hook::gl::SwapBuffers=(SwapBuffers_t)LM_MakeTrampoline(gl::SwapBuffers, 5);
  LM_DetourCode(gl::SwapBuffers, &hook::gl::SwapBuffers, LM_DETOUR_JMP32);
}
```

**Comment by rdbo** [comment]
```c
oSwapBuffers = (SwapBuffers_t)LM_MakeTrampoline(<swap buffers addr>, <size of trampoline>);
LM_DetourCode(<swap buffers addr>, hkSwapBuffers, <detour type>);
```

// after use
```c
LM_DestroyTrampoline(oSwapBuffers);
```

**Comment by laper32** [comment]
hmm, looks like kind of this?

```cpp

using SwapBuffers_t = BOOL(__stdcall*)(_In_ HDC hDC);

lm_module_t opengl32;

namespace gl
{
  void* SwapBuffers;
}

namespace hook
{
  namespace gl
  {
    SwapBuffers_t SwapBuffers;
  }
}

BOOL __stdcall hook_SwapBuffers(_In_ HDC hDC)
{
  return hook::gl::SwapBuffers(hDC);
}

BOOL WINAPI MainThread(HMODULE hModule)
{
  AllocConsole();
  freopen("CONOUT$", "w", stdout);

  LM_GetModule(LM_MOD_BY_STR, (void*)LM_STR("OPENGL32.dll"), &opengl32);
  SwapBuffers = LM_GetSymbol(opengl32, (lm_cstring_t)"wglSwapBuffers");

  hook::gl::SwapBuffers = (SwapBuffers_t)LM_MakeTrampoline(gl::SwapBuffers, 5);
  LM_DetourCode(gl::SwapBuffers, hook_SwapBuffers, LM_DETOUR_JMP32);

  while (!(GetAsyncKeyState(VK_END) & 1));

  LM_DestroyTrampoline(hook::gl::SwapBuffers);
  fclose(stdout);
  FreeConsole();
  FreeLibraryAndExitThread(hModule, 0);
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD dwReason, LPVOID lpReserved)
{
  switch (dwReason)
  {
    case DLL_PROCESS_ATTACH:
      if (HANDLE hndl = CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)MainThread, hModule, 0, nullptr))
      {
        CloseHandle(hndl);
      }
      break;
    default: break;
  }
  return TRUE;
}

```

**Comment by laper32** [comment]
> hmm, looks like kind of this?
> 
> ```c++
> using SwapBuffers_t = BOOL(__stdcall*)(_In_ HDC hDC);
> 
> lm_module_t opengl32;
> 
> namespace gl
> {
>   void* SwapBuffers;
> }
> 
> namespace hook
> {
>   namespace gl
>   {
>     SwapBuffers_t SwapBuffers;
>   }
> }
> 
> BOOL __stdcall hook_SwapBuffers(_In_ HDC hDC)
> {
>   return hook::gl::SwapBuffers(hDC);
> }
> 
> BOOL WINAPI MainThread(HMODULE hModule)
> {
>   AllocConsole();
>   freopen("CONOUT$", "w", stdout);
> 
>   LM_GetModule(LM_MOD_BY_STR, (void*)LM_STR("OPENGL32.dll"), &opengl32);
>   gl::SwapBuffers = LM_GetSymbol(opengl32, (lm_cstring_t)"wglSwapBuffers");
> 
>   hook::gl::SwapBuffers = (SwapBuffers_t)LM_MakeTrampoline(gl::SwapBuffers, 5);
>   LM_DetourCode(gl::SwapBuffers, hook_SwapBuffers, LM_DETOUR_JMP32);
> 
>   while (!(GetAsyncKeyState(VK_END) & 1));
> 
>   LM_DestroyTrampoline(hook::gl::SwapBuffers);
>   fclose(stdout);
>   FreeConsole();
>   FreeLibraryAndExitThread(hModule, 0);
> }
> 
> BOOL APIENTRY DllMain(HMODULE hModule, DWORD dwReason, LPVOID lpReserved)
> {
>   switch (dwReason)
>   {
>     case DLL_PROCESS_ATTACH:
>       if (HANDLE hndl = CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)MainThread, hModule, 0, nullptr))
>       {
>         CloseHandle(hndl);
>       }
>       break;
>     default: break;
>   }
>   return TRUE;
> }
> ```

However I don't really know why it triggered 0xc0000005 win32 exception....

**Comment by laper32** [comment]
Further information updated, about crashes.
