### ISSUE TITLE
Windows LM_LoadModuleEx doesn't return module

### ISSUE THREAD

**Issue by llyama** [rdbo/libmem#242]
The [LM_LoadModuleEx](https://github.com/rdbo/libmem/blob/c8307d0cdf5e50b27defa37761acab9e8eb6a1be/src/win/module.c#L100) implementation for Windows doesn't set the `module_out` parameter to anything.

**Comment by rdbo** [comment]
Funny that the unit tests didn't catch this
![image](https://github.com/rdbo/libmem/assets/57117082/ab1c4ed1-0e00-4a4a-b6a0-020df22d944b)
Well spotted, thanks

**Comment by llyama** [comment]
Fixed in 5.0.1
