### ISSUE TITLE
LM_FindModule BUG?

### ISSUE THREAD

**Issue by haxjp** [rdbo/libmem#251]
environment:
OS Windows11 23H2
Compiler MSVC
Using library libmem-5.0.1-x86_64-windows-msvc-static-md

When I copied the C/C++ example ( process name has been changed.) and ran it, I got the problem that game_mod.base was not initialized.
Instead, wecan use LM_LoadModule to get the base address.

**Comment by rdbo** [comment]
The example in the README is just a showcase, it won't work
You have to use it according to the process you are targetting
