### ISSUE TITLE
TODO: fix libmem

### ISSUE THREAD

**Issue by rdbo** [rdbo/libmem#26]
`libmem` is a project I have work on and off for a very long time. It has had many different versions, one completely different than the other, because the more I got better at programming, the more ideas I had to make it better.
Unfortunately, libmem has become practically unmaintainable, mainly for the following reasons:
- It is not modular: everything is on libmem.h and libmem.c, including the code for all different platforms and architectures, making it a mess with all the preprocessor directives.
- It has too many features: libmem should have followed the KISS process (Keep It Simple Stupid), instead of adding too many features, such as multiple different hooking methods, debugger functions, overly-complicated code injection (such as the LM_FunctionCallEx).

So how to fix it?
My plan is to do the following:
- Modulate libmem: I could do that by separating the OS-specific and Arch-specific code, and rely on better written third-party libraries, such as the addition of the `capstone` and `keystone` libraries instead of writing my own assembler/disassembler. I'm not sure yet how am I going to modulate it in practice because everything is so entangled together, but I'm sure there is a way.
- Remove overkill features: offer only one hooking method per architecture, no debugging functions as they're not the main focus of libmem, etc.
- Follow a Unix-like directory structure for the project: instead of putting everything under the `libmem` folder, there should be a `include` and `source` folders (like in `capstone` and `keystone`, similar to the Unix `/usr` directory), since the library should be compiled first and then included into your project, and not compiled along with your project.
- Make it 'installable': At least on Unix-like systems, there should be a way to install the libmem shared library into `/usr/local/lib` to make it easier for linking the library.
- Add better documentation: there used to be a documentation, but since the project started changing very often, I deleted the old one. After all of other points are fixed, there should be a very detailed documentation about all libmem APIs to make developer's lives easier.

These are only the stuff I could remember right now, and I hope I can close this issue in the future.
If you want to contribute, make a pull request.
There's a lot of work ahead of libmem.

**Comment by cynikkk** [comment]
I thought the project was abandoned, happy to see milestones !
Keep up the good work :)

**Comment by rdbo** [comment]
I would say this is done: it has been modulated, there is documentation, Rust support, Python support, automatic hooking, it can be installed, no more overkill features...
Everything looks good now, 4.0 is coming.
