### ISSUE TITLE
Can lm_process_t provide an icon attribute of size 32x32?

### ISSUE THREAD

**Issue by ytrsoft** [rdbo/libmem#263]

**Comment by rdbo** [comment]
The concept of an icon in a process is Windows-only
Other operating systems have it, but it's not something inherit to processes
Also would be a waste of memory since there is no logical operation libmem can do with a process icon
So no

**Comment by commonuserlol** [comment]
Hello, I am an authorized libmem's bug ~~introducer~~ fixer,

No, unfortunately we can't add this as the windows must die.

Thanks,
Polite as always,
libmemleaddev
