### ISSUE TITLE
LM_HookCode  (windows x86)  not working

### ISSUE THREAD

**Issue by lgztx96** [rdbo/libmem#265]
use https://github.com/rdbo/libmem/releases/download/5.0.3/libmem-5.0.3-x86_64-windows-msvc-static-md.tar.gz

LNK 2001 error
![Snipaste_2024-12-02_01-20-15](https://github.com/user-attachments/assets/078a94bc-b424-4d79-a48d-138ada03871f)

use https://github.com/rdbo/libmem/releases/download/5.0.3/libmem-5.0.3-x86_64-windows-msvc-shared-md.tar.gz

debug mode
![Snipaste_2024-12-02_01-13-54](https://github.com/user-attachments/assets/0b26e61a-cb2e-4879-a31d-b20a32ca445f)

release mode
![Snipaste_2024-12-02_01-14-49](https://github.com/user-attachments/assets/b2998de8-40f5-4861-a8cc-0508e6adf49c)

**Comment by rdbo** [comment]
Windows puts dummy functions as the addresses instead of the real function right away
The address of my_function will just be a jump to the actual my_function
Try getting the actual address first before hooking

**Comment by lgztx96** [comment]
> Windows puts dummy functions as the addresses instead of the real function right away The address of my_function will just be a jump to the actual my_function Try getting the actual address first before hooking

test code:
```
#include <iostream>
#include <libmem/libmem.hpp>
#include <polyhook2/Detour/NatDetour.hpp>
#include <MinHook.h>
#include <print>

static uint64_t my_function_tramp;

void my_function(int number, char letter)
{
	std::cout << "MyNumber: " << number << std::endl;
	std::cout << "MyLetter: " << letter << std::endl;
}

void hk_my_function(int number, char letter)
{
	std::cout << "Hooked 'my_function'!" << std::endl;
	std::cout << "Original Number: " << number << std::endl;
	std::cout << "Original Letter: " << letter << std::endl;
	std::cout << "Calling original function with custom parameters..." << std::endl;

	reinterpret_cast<void(*)(int, char)>(my_function_tramp)(1337, 'W');
}

void minhook() {
	MH_Initialize();
	if (MH_CreateHook(&my_function, &hk_my_function, (void**)&my_function_tramp) == MH_OK) {
		MH_EnableHook(&my_function);
		my_function(10, 'L');
		MH_DisableHook(&my_function);
		MH_RemoveHook(&my_function);
	}

	MH_Uninitialize();
}

void polyhook() {
	PLH::NatDetour detour = PLH::NatDetour(
		reinterpret_cast<uint64_t>(&my_function),
		reinterpret_cast<uint64_t>(&hk_my_function), &my_function_tramp);

	detour.hook();
	my_function(10, 'L');
	detour.unHook();
}

void lm_hook() {
	if (auto tramp = libmem::HookCode(
		reinterpret_cast<libmem::Address>(&my_function),
		reinterpret_cast<uint64_t>(&hk_my_function))) {
		my_function_tramp = static_cast<uint64_t>(tramp->address);
		my_function(10, 'L');
		libmem::UnhookCode(reinterpret_cast<libmem::Address>(&my_function), *tramp);
	}
}

int main()
{
	std::print("polyhook start\n");
	polyhook();
	std::print("minhook start\n");
	minhook();
	std::print("lm hook start\n");
	lm_hook();

	return 0;
}
```
debug mode 
minhook working,  &emsp; polyhook working,&emsp;  libmem not working(crash)

![Snipaste_2024-12-02_10-20-39](https://github.com/user-attachments/assets/f042fe5f-c8a3-43eb-bc81-4458608e0930)

release mode 
minhook not working,&emsp;  polyhook working,&emsp;  libmem not working
![Snipaste_2024-12-02_10-20-59](https://github.com/user-attachments/assets/390e4f3c-a33c-444e-ba6a-7b476282e31a)

use __declspec(noinline),  all libraries will work

perhaps it can be optimized?

**Comment by rdbo** [comment]
Can you dump the instructions with Cheat Engine before and after the hook?

**Comment by lgztx96** [comment]
> Can you dump the instructions with Cheat Engine (or any other tool) before and after the hook?

I tested the crash in debug mode, release mode actually works. The reason why it was not called was because the compiler inline called it
debug mode:
![src](https://github.com/user-attachments/assets/5f4bdd12-7e8d-41d5-b4bc-16aad6725830)
![Snipaste_2024-12-04_10-05-14](https://github.com/user-attachments/assets/194bac2a-1be0-4581-a149-364aa87faf35)

my_function remains unchanged before and after the hook, and the trampoline jumps to a invailed address.

**Comment by rdbo** [comment]
What if you print the address of the function in your code and look at that address in the debugger? Like I said sometimes MSVC places a dummy function as the function instead of the actual function code, so maybe even though that is the function, the thing you are hooking is the dummy
I say this because in order to test libmem, I have to resolve the dummy pointer to get the real function address before hooking on Windows so I expect that you'll be facing the same issue

**Comment by lgztx96** [comment]
> What if you print the address of the function in your code and look at that address in the debugger? Like I said sometimes MSVC places a dummy function as the function instead of the actual function code, so maybe even though that is the function, the thing you are hooking is the dummy I say this because in order to test libmem, I have to resolve the dummy pointer to get the real function address before hooking on Windows so I expect that you'll be facing the same issue

It seems so.
![Snipaste_2024-12-06_21-18-23](https://github.com/user-attachments/assets/e48c1546-9730-4ff3-9460-7a35ce186e4a)
![Snipaste_2024-12-06_21-15-57](https://github.com/user-attachments/assets/17adf1b2-3870-40eb-918c-7ff740f1a72a)
