### ISSUE TITLE
Compilation error occurred

### ISSUE THREAD

**Issue by MY-Git-Li** [rdbo/libmem#267]
Development environment:
ibmem-5.0.3-x86_64-windows-msvc-static-md
vs2022

configure:
The directory containing VC++has been configured in the VS2022 project as follows:
$(SolutionDir)TTT\libmem-5.0.3-x86_64-windows-msvc-static-md\include;

The configuration of the additional library directory in the linker's routine is as follows:
$(SolutionDir)TTT\libmem-5.0.3-x86_64-windows-msvc-static-md\lib\$(ConfigurationName);

Attach dependency configurations to the input of the linker as follows:
libmem.lib

The code is as follows:
```
#include <iostream>
#include "libmem/libmem.h"
int main()
{
std::cout << "Hello World!\n";
lm_module_t moduled;
LM_FindModule("user32.dll", &moduled);
}
```
Error after compilation:
error LNK2001: unresolved external symbol __imp_LM_FindModule

**Comment by rdbo** [comment]
Check that your project is in /MT mode as well

**Comment by MY-Git-Li** [comment]
I have set /MT,/MTd,/MD, and/MDd separately, but after each compilation, I still encountered error LNK2001: Unresolved external symbol __imp_LM-FindModule

**Comment by luadebug** [comment]
You could try xmake.
```lua
add_rules("mode.debug", "mode.release")
set_languages("c++17")
add_requires("libmem 5.0.3")
target("untitled")
    add_packages("libmem")
    set_kind("binary")
    add_files("src/*.cpp")
```
```cpp
#include <iostream>
#include <optional>
#include <libmem/libmem.hpp>
#include <libmem/libmem.h>

using namespace std;
using namespace libmem;

int main()
{
    std::cout << "Testing C api!" << std::endl;
    lm_module_t module_c;
    LM_FindModule("user32", &module_c);
    if (module_c.size > 0)
    {
        std::cout << "Current process has user32.dll module!" << std::endl;
        std::cout << "base = " << module_c.base << "\t end = " << module_c.end << "\t name = " << module_c.name << "\t path = " << module_c.path << "\t size = " << module_c.size;
    }
    else
    {
        std::cout << "Current process has not user32.dll module!" << std::endl;
    }
    std::cout << "Testing C++ api!" << std::endl;
    optional<libmem::Module> module_cpp = libmem::FindModule("user32");
    if (module_cpp.has_value())
    {
        libmem::Module module_cpp_v = module_cpp.value();
        std::cout << "Current process has user32.dll module!" << std::endl;
        std::cout << "base = " << module_cpp_v.base << "\t end = " << module_cpp_v.end << "\t name = " << module_cpp_v.name << "\t path = " << module_cpp_v.path << "\t size = " << module_cpp_v.size;
    }
    else
    {
        std::cout << "Current process has not user32.dll module!" << std::endl;
    }
    return 0;
}
```

**Comment by MY-Git-Li** [comment]
Thank you for your suggestion. I did not install xmake, so I used vcpkg for the experiment,
I use
```
vcpkg install libmem:x64-windows
vcpkg install libmem:x64-windows-static-md
```
Install x64 dynamic libraries and MD static libraries.
Write the following code to conduct experiments:

```
#include <iostream>
#include "libmem/libmem.h"
int main()
{
std::cout << "Hello World!\n";
lm_module_t moduled;
LM_FindModule("user32.dll", &moduled);
}
```
When I use the x64 dynamic library, it works.
However, when I was using the static library of MD, I still encounter link errors:
error LNK2001: unresolved external symbol __imp_LM_FindModule

**Comment by rdbo** [comment]
@MY-Git-Li 
There's also a difference between Debug (/MDd or /MTd) and Release (/MD or /MT), maybe that could be an issue as well
In any case, I made a new release (5.0.4) which may fix this issue

**Comment by MY-Git-Li** [comment]
@rdbo 
Yes, it worked, this update worked
